# This is a Flutter plugin pubspec file.
name: simple_sip_client
description: A Flutter plugin for SIP paging from Windows clients.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.12.2
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  record: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: SimpleSipClientPlugin
